// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backgroundTasks.sql

package db

import (
	"context"
)

const cleanUpOldNotes = `-- name: CleanUpOldNotes :exec
delete from notes
where created_at < now() - interval '10 minutes'
and content = ''
`

func (q *Queries) CleanUpOldNotes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanUpOldNotes)
	return err
}
