// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Note struct {
	ID        string
	OwnerID   string
	Title     string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             string
	Email          string
	Username       string
	HashedPassword string
}
