// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
)

const createNote = `-- name: CreateNote :one
insert into notes (id, owner_id, title, content)
values ($1, $2, $3, $4)
returning id, owner_id, title, content, created_at, updated_at
`

type CreateNoteParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Content,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
delete from notes
where id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
select id, owner_id, title, content, created_at, updated_at
from notes
where id = $1
`

func (q *Queries) GetNoteByID(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotesByOwnerID = `-- name: GetNotesByOwnerID :many
select id, owner_id, title, content, created_at, updated_at
from notes
where owner_id = $1
order by created_at desc
`

func (q *Queries) GetNotesByOwnerID(ctx context.Context, ownerID string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
update notes
set title = $2, content = $3, updated_at = now()
where id = $1
returning id, owner_id, title, content, created_at, updated_at
`

type UpdateNoteParams struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.ID, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
