// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_notes.sql

package db

import (
	"context"
	"time"
)

const addNoteUser = `-- name: AddNoteUser :one
insert into share_notes (user_id, note_id, permissions)
values ($1, $2, $3)
returning user_id, note_id, permissions
`

type AddNoteUserParams struct {
	UserID      string `json:"user_id"`
	NoteID      string `json:"note_id"`
	Permissions string `json:"permissions"`
}

func (q *Queries) AddNoteUser(ctx context.Context, arg AddNoteUserParams) (ShareNote, error) {
	row := q.db.QueryRowContext(ctx, addNoteUser, arg.UserID, arg.NoteID, arg.Permissions)
	var i ShareNote
	err := row.Scan(&i.UserID, &i.NoteID, &i.Permissions)
	return i, err
}

const getNoteUsers = `-- name: GetNoteUsers :many
select u.id, u.email, u.username, sn.permissions
from users u
join share_notes sn on u.id = sn.user_id
where sn.note_id = $1
`

type GetNoteUsersRow struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	Username    string `json:"username"`
	Permissions string `json:"permissions"`
}

func (q *Queries) GetNoteUsers(ctx context.Context, noteID string) ([]GetNoteUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getNoteUsers, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNoteUsersRow{}
	for rows.Next() {
		var i GetNoteUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedNoteByID = `-- name: GetSharedNoteByID :one
select n.id, n.title, n.content, n.created_at, n.updated_at, sn.permissions
from notes n
join share_notes sn on n.id = sn.note_id
where sn.user_id = $1 and n.id = $2
`

type GetSharedNoteByIDParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type GetSharedNoteByIDRow struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Permissions string    `json:"permissions"`
}

func (q *Queries) GetSharedNoteByID(ctx context.Context, arg GetSharedNoteByIDParams) (GetSharedNoteByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSharedNoteByID, arg.UserID, arg.ID)
	var i GetSharedNoteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Permissions,
	)
	return i, err
}

const getSharedNoteByOwnerID = `-- name: GetSharedNoteByOwnerID :many
select sn.note_id
from share_notes sn
join notes n on n.id = sn.note_id
where n.owner_id = $1
`

func (q *Queries) GetSharedNoteByOwnerID(ctx context.Context, ownerID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSharedNoteByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var note_id string
		if err := rows.Scan(&note_id); err != nil {
			return nil, err
		}
		items = append(items, note_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedNotesByUserID = `-- name: GetSharedNotesByUserID :many
select n.id, n.title, n.content, n.created_at, n.updated_at, sn.permissions
from notes n
join share_notes sn on n.id = sn.note_id
where sn.user_id = $1
`

type GetSharedNotesByUserIDRow struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Permissions string    `json:"permissions"`
}

func (q *Queries) GetSharedNotesByUserID(ctx context.Context, userID string) ([]GetSharedNotesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getSharedNotesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharedNotesByUserIDRow{}
	for rows.Next() {
		var i GetSharedNotesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissionForNote = `-- name: GetUserPermissionForNote :one
select sn.permissions
from share_notes sn
where sn.user_id = $1 and sn.note_id = $2
`

type GetUserPermissionForNoteParams struct {
	UserID string `json:"user_id"`
	NoteID string `json:"note_id"`
}

func (q *Queries) GetUserPermissionForNote(ctx context.Context, arg GetUserPermissionForNoteParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPermissionForNote, arg.UserID, arg.NoteID)
	var permissions string
	err := row.Scan(&permissions)
	return permissions, err
}

const removeNoteUser = `-- name: RemoveNoteUser :exec
delete from share_notes where user_id = $1 and note_id = $2
`

type RemoveNoteUserParams struct {
	UserID string `json:"user_id"`
	NoteID string `json:"note_id"`
}

func (q *Queries) RemoveNoteUser(ctx context.Context, arg RemoveNoteUserParams) error {
	_, err := q.db.ExecContext(ctx, removeNoteUser, arg.UserID, arg.NoteID)
	return err
}

const updateNoteUserPermissions = `-- name: UpdateNoteUserPermissions :exec
update share_notes set permissions = $3 where user_id = $1 and note_id = $2
`

type UpdateNoteUserPermissionsParams struct {
	UserID      string `json:"user_id"`
	NoteID      string `json:"note_id"`
	Permissions string `json:"permissions"`
}

func (q *Queries) UpdateNoteUserPermissions(ctx context.Context, arg UpdateNoteUserPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, updateNoteUserPermissions, arg.UserID, arg.NoteID, arg.Permissions)
	return err
}
